### ISSUE TITLE
换了个下载地址，出错

### ISSUE THREAD

**Issue by qqtanwei** [Othershe/DUtil#2]
http://dlied5.myapp.com/myapp/1105148805/cqsj/10022707_com.tencent.cqsj_h100_0.20.0.45.apk
可以暂停，继续报错。

**Comment by Othershe** [comment]
用你的地址测试了，没发现问题

**Comment by qqtanwei** [comment]
Nexu5  6.0   第一次暂停  再 继续就报错
HTC  第二次暂停 再继续报错 
startSaveRangeFile 这个方法开始报错
 java.io.IOException: mmap failed: ENOMEM (Out of memory)  这是log

**Comment by YamingZhao** [comment]
请问下更换了下载url，为什么会有repsonse返回401？

**Comment by Othershe** [comment]
权限问题

**Comment by YamingZhao** [comment]
还有一个问题请教下楼主，单从singleTaskActivity来看的话，将DownloadManager的childTaskCount设置为3，会启用三个request来请求response，但是这个应该不算多线程下载吧？ 仅仅是提高下载速度吧？

**Comment by Othershe** [comment]
一个request就是一个子线程哦

**Comment by YamingZhao** [comment]
一个FileTask才是一个线程吧？就是一个fileTask本身就会开多个线程来下载同一个文件，project里也可以有多个的FileTask下载不同的文件？一个request是一个线程，这是Okhttp实现的吗？

**Comment by YamingZhao** [comment]
看到了你用的异步请求，所以相当于每一个request是一个独立的子线程。
