### ISSUE TITLE
DownloadManager的单例问题和context可能带来的memory leak

### ISSUE THREAD

**Issue by YamingZhao** [Othershe/DUtil#4]
有几个问题想请教下：
1. 为什么使用Dutil 去init一个DBuilder，Dutil的init(Context context)方法不直接放在Dbuilder里面有理由吗?
2. DownloadManager为什么使用volatile加类锁？Context 被静态对象持有是不是会出现memory leak？

- private volatile static DownloadManger downloadManager;
- public static DownloadManger getInstance(Context context) {
-         if (downloadManager == null) {
-             synchronized (DownloadManger.class) {
-                 if (downloadManager == null) {
-                     downloadManager = new DownloadManger(context);
-                 }
-             }
-         }
-         return downloadManager;
-     }
-}

**Comment by Othershe** [comment]
1、DBuilder是做下载配置的，Context的初始化放在里边略生硬，当然也有个人习惯的原因。
2、在jdk1.5之前，可能会出现单例双重检查锁定的判断失效，所以要添加使用volatile；memory leak确实有些问题

**Comment by YamingZhao** [comment]
恩，对于这个memory leak有没有什么好的解决办法？
