### ISSUE TITLE
DownloadManger 单例问题

### ISSUE THREAD

**Issue by itsuantou** [Othershe/DUtil#7]
DBuilder 构建出的 DownloadManger 为单例 . 

多线程时对DownloadManger进行多次 init 操作,
DownloadManager.downloadData为非安全对象. 
是否可使用 DownloadManger.addDonloadTask(DownloadData downloadData) 形式对下载数据的对象进行保存? 亦或者通过 url 进行 map 映射?

同时 context 是否可以使用 context.getApplicationContext 避免Activity 内存泄漏?

**Comment by Othershe** [comment]
1、downloadData是通过url进行map映射保存的
2、context 可以传入getApplicationContext()

**Comment by itsuantou** [comment]
DownloadManager 只针对一个对应的 DownloadData 进行下载的操作, 那多个 DownloadData 对象同时进行下载操作怎样保证下载对象是对应的 DownloadData 封装的文件呢?

```java
  public void init(String url, String path, String name, int childTaskCount) {
        downloadData = new DownloadData();
        downloadData.setUrl(url);
        downloadData.setPath(path);
        downloadData.setName(name);
        downloadData.setChildTaskCount(childTaskCount);
    }

```

```java 
    public DownloadManger start(DownloadCallback downloadCallback){}
```

**Comment by itsuantou** [comment]
建议: 
```java
    private DownloadManger(Context context) {
        this.context = context.getApplicationContext();
    }

```
是否不用担心传递的 Context 是否为 `Activity` 导致的内存泄漏

**Comment by Othershe** [comment]
多谢你的建议
